#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND="wayland"

# Browsers HW acceleration
export MOZ_ENABLE_WAYLAND=1
export MOZ_DISABLE_RDD_SANDBOX=1

export PATH=$HOME/.local/bin:$PATH
export EDITOR="nvim"
export TERMINAL="kitty"
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export MAKEFLAGS="-j$(nproc)"

exec Hyprland
