Threshold = 1
DisplayMonitorSources = false
EnableUpdates = true
GuiltTripped = false
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.pci-0000_0c_00.3.analog-stereo"
LastUsedOutput = ""
