Threshold = 5
DisplayMonitorSources = false
EnableUpdates = true
GuiltTripped = false
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.pci-0000_04_00.6.analog-stereo"
LastUsedOutput = ""
